addons:
  apt:
    sources:
      - debian-sid
    packages:
      - cmake
      - build-essential
      - zlib1g-dev
      - libgloox-dev
      - libqt5quick5
      - libqt5quickcontrols2-5
      - libqt5quickwidgets5
      - libqt5qml5
      - libqt5gui5
      - libqt5core5a
      - qtdeclarative5-dev
      - qttools5-dev
      - qt5-default
      - qtquickcontrols2-5-dev
      - kirigami2-dev
      - ubuntu-archive-keyring

script:
  - cd utils
  - travis-build.sh
