language: minimal
compiler: gcc
services:
  - docker
cache:
  ccache: true
  directories:
    - /var/cache/apt/archives
sudo: required
dist: bionic
install:
  - ./utils/travis/dependencies.sh
script:
  - . utils/travis/common.sh
  - env_setup
  - ./utils/travis/build.sh
matrix:
  include:
    - env: BUILD_SYSTEM=cmake
      git:
        submodules: false

    - env: PLATFORM=ubuntu-touch
      git:
        submodules: false
      # only cache apt archives
      cache:
        directories:
          - /var/cache/apt/archives
notifications:
  email: false
