language: cpp
compiler: gcc
services:
  - docker
cache:
  ccache: true
  directories:
    - /var/cache/apt/archives
sudo: required
dist: trusty
install:
  - ./utils/travis/dependencies.sh
script:
  - . utils/travis/common.sh
  - env_setup
  - ./utils/travis/build.sh
matrix:
  include:
    - env: PLATFORM=linux-desktop BUILD_SYSTEM=qmake
    - env: PLATFORM=linux-desktop BUILD_SYSTEM=cmake
    - env: PLATFORM=ubuntu-touch BUILD_SYSTEM=cmake
notifications:
  email: false
